### ISSUE TITLE
Error in signatures computation

### ISSUE THREAD

**Issue by inoelloc** [DassHydro-dev/smash#28]
Trying to compute signatures with model.signatures and there is the traceback:
```
Traceback (most recent call last):
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/get_signatures.py", line 71, in <module>
    run(row, setup, batch_name, res_dir)
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/get_signatures.py", line 43, in run
    res = model.signatures(sign=["Epf", "Elt"], obs_comp=True)
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/smash/smash/core/model.py", line 1563, in signatures
    return _signatures(self, cs, es, obs_comp, **event_seg)
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/smash/smash/core/signatures.py", line 480, in _signatures
    return _signatures_comp(
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/smash/smash/core/signatures.py", line 383, in _signatures_comp
    list_events = _events_grad(
  File "/home/RHAX/UTILISATEURS/francois.colleoni/CDD_Explore2/Oth/Article1/smash/smash/core/_event_segmentation.py", line 259, in _events_grad
    end = i + np.argmin(dflow)
  File "<__array_function__ internals>", line 180, in argmin
  File "/local/AIX/fcolleoni/anaconda3/envs/smash-dev/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 1312, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/local/AIX/fcolleoni/anaconda3/envs/smash-dev/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

**Comment by nghi-truyen** [comment]
The issue arises when an event is selected in the last time steps of the hydrogram.
